name: Deploy infra & lambdas

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Python (for zipping; optional)
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create deploy directory & zip lambdas
        run: |
          mkdir -p deploy
          zip -j deploy/new_post.zip lambda/handler.py
          zip -j deploy/convert_to_audio.zip lambda/convert_to_audio.py
          zip -j deploy/get_post.zip lambda/get_post.py
          ls -lh deploy

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        working-directory: terraform
        run: |
          if [ -n "${{ secrets.TFSTATE_BUCKET }}" ]; then
            terraform init -input=false \
              -backend-config="bucket=${{ secrets.TFSTATE_BUCKET }}" \
              -backend-config="key=polly-app/terraform.tfstate" \
              -backend-config="region=${{ secrets.AWS_REGION }}" \
              -backend-config="dynamodb_table=${{ secrets.TFSTATE_LOCK_TABLE }}"
          else
            terraform init -input=false
          fi

      - name: Terraform Format & Validate
        working-directory: terraform
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_LOG: DEBUG   # enable detailed debug logging
        run: terraform apply -auto-approve -input=false
        timeout-minutes: 15   
