name: Deploy infra & lambdas

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Python (for zipping; optional)
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create deploy directory & zip lambdas
        run: |
          mkdir -p deploy
          zip -j deploy/new_post.zip lambda/handler.py
          zip -j deploy/convert_to_audio.zip lambda/convert_to_audio.py
          zip -j deploy/get_post.zip lambda/get_post.py
          ls -lh deploy

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        working-directory: terraform
        run: |
          if [ -n "${{ secrets.TFSTATE_BUCKET }}" ]; then
            terraform init -input=false \
              -backend-config="bucket=${{ secrets.TFSTATE_BUCKET }}" \
              -backend-config="key=polly-app/terraform.tfstate" \
              -backend-config="region=${{ secrets.AWS_REGION }}" \
              -backend-config="dynamodb_table=${{ secrets.TFSTATE_LOCK_TABLE }}"
          else
            terraform init -input=false
          fi

      - name: Terraform Format & Validate
        working-directory: terraform
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Import existing resources
        working-directory: terraform
        run: |
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_dynamodb_table.posts bobby_posts || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_iam_role.lambda_new_post_role bobby_lambda_new_post_role || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_iam_role.lambda_convert_role bobby_lambda_convert_role || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_iam_role.lambda_get_role bobby_lambda_get_role || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_s3_bucket.mp3_bucket text2speech-bobby-20250916-unique1234 || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_lambda_function.new_post bobby-new-post || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_lambda_function.convert_to_audio bobby-convert-to-audio || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_lambda_function.get_post bobby-get-post || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_lambda_permission.apigw_invoke_new_post bobby-new-post/AllowAPIGatewayInvokeNewPost || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_lambda_permission.apigw_invoke_get_post bobby-get-post/AllowAPIGatewayInvokeGetPost || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_lambda_permission.apigw_invoke_convert_to_audio bobby-convert-to-audio/AllowAPIGatewayInvokeConvertToAudio || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_lambda_permission.allow_sns_invoke bobby-convert-to-audio/AllowExecutionFromSNS || true
          terraform import -var="aws_region=us-east-1" -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" -var="db_table_name=bobby_posts" -var="sns_topic_name=bobby-post-topic" aws_s3_bucket.website_bucket text2speech-bobby-20250916-unique1234-website || true

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_LOG: DEBUG   # enable detailed debug logging
        run: |
          terraform apply -auto-approve -input=false \
            -var="aws_region=us-east-1" \
            -var="mp3_bucket_name=text2speech-bobby-20250916-unique1234" \
            -var="db_table_name=bobby_posts" \
            -var="sns_topic_name=bobby-post-topic"
        timeout-minutes: 15

      - name: Get API Gateway URL and update website
        working-directory: terraform
        run: |
          API_URL=$(terraform output -raw api_base_url)
          sed -i 's|YOUR_API_ID|'"$(echo $API_URL | cut -d'/' -f3 | cut -d'.' -f1)"'|g' ../website/scripts.js
          
      - name: Upload website to S3
        run: |
          aws s3 sync website/ s3://text2speech-bobby-20250916-unique1234-website/ --delete   
